version: '3'
services:
  mongo:
    container_name: cc-mongo
    image: mongo
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - cubingcontests-db-dev:/data/db:rw
      # - ./mongo_init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmindev
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmindev123
      - MONGO_INITDB_DATABASE=cubingcontests
    restart: unless-stopped
  mongo-express:
    container_name: cc-mongo-express
    image: mongo-express
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cc-mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmindev
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadmindev123
    depends_on:
      - mongo
    restart: unless-stopped
  cc-api:
    container_name: cc-api
    image: cubingcontests-api
    networks:
      - cubingcontests-dev
    ports:
      - 127.0.0.1:6000:6000
    environment:
      # This is different from the URI in server/src/app.module.ts, because that one uses @localhost
      - MONGODB_URI=mongodb://mongoadmindev:mongoadmindev123@cc-mongo:27017/admin
    depends_on:
      - mongo
    restart: unless-stopped
networks:
  cubingcontests-dev:
volumes:
  cubingcontests-db-dev:
    # Tells docker to create the storage for the volume on the local file system
    driver: local
