services:
  mongo:
    container_name: cc-mongo
    image: mongo
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - cubingcontests-db:/data/db:rw
      # The scripts in docker-entrypoint-initdb.d are run when the container and volume are first created
      - mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ADMIN_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ADMIN_PASSWORD
      - MONGO_DEV_USERNAME=$MONGO_DEV_USERNAME
      - MONGO_DEV_PASSWORD=$MONGO_DEV_PASSWORD
    restart: always

  api:
    container_name: cc-api
    image: denimint/cubingcontests-api:$VERSION
    networks:
      - cubingcontests
    env_file: .env
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$BACKEND_PORT
      - MONGO_DEV_USERNAME=$MONGO_DEV_USERNAME
      - MONGO_DEV_PASSWORD=$MONGO_DEV_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - BASE_URL=$BASE_URL
    depends_on:
      - mongo
    restart: always

  client:
    container_name: cc-client
    image: denimint/cubingcontests-client:$VERSION
    networks:
      - cubingcontests
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - ENVIRONMENT=$NODE_ENV
    depends_on:
      - mongo
      - api
    restart: always

networks:
  cubingcontests:
volumes:
  cubingcontests-db:
    driver: local
  mongo-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_init
